### ISSUE TITLE
Subquery returns more than 1 row

### ISSUE THREAD

**Issue by webstylr** [kowsar89/woocommerce-filter-orders-by-product#1]
Hi!
First of all: thanks for the plugin!

With the latest woocommerce (2.4.10), the plugin stopped working.
If i go to Orders and select a product, all i get is a Database error that says
    `Subquery returns more than 1 row`

Is there a chance for an update?

Thanks!

**Comment by webstylr** [comment]
On further investigation, the plugin now only works if there are only orders containing 1 product.
If you have orders that contain different products, the the error occurs.

**Comment by kowsar89** [comment]
This is fixed in version 2
